key "rndc-key" {
	algorithm hmac-sha256;
	secret "5ILo8qU+9PtL8iDg4ob7jLm+s/nDft0CDX2BbQvwQ60=";
};

include "/etc/update.key";

options {
    default-server 192.168.14.10;
    default-port 953;
    default-key "update-key";
};